SOURCES += src/comms.c \
src/debug.c \
src/sleeping.c \
src/spi.c \
src/radio/ieee_frame.c \
src/radio/rf212_functions.c \
src/radio/radio.c \
src/radio/rf212.c \
src/radio/radio_functions.c \
src/pwrmon.c \
src/main.c \
src/radio_init_service.c \
src/audio/wm8737.c \
src/audio/i2c.c \
src/audio/sampling.c \
src/upload.c \
src/console.c \
src/fft.c \
src/envelope.c \
src/settings.c \
src/led.c \
src/mem/wipe_mem.c \
src/mem/invalidate.c \
src/mem/checksum.c \
src/mem/write.c \
src/mem/flash.c \
src/mem/btree.c \
src/timing.c \
